app:
  env: dev
  name: lakehouse-admin

cloud:
  aws:
    defaults:
      endpoint: ""
      region: "eu-central-1"

httpserver:
  default:
    port: 8081
    mode: release
    timeout:
      read: 10m
      write: 10m

iceberg:
  catalog: lakehouse
  default_database: main
  needs_optimize_delay: 96h # 4 days

kube:
  client_mode: "in-cluster"
  context: "arn:aws:eks:eu-central-1:{aws.account_id}:cluster/{aws.organizational_unit}-marketing"

log:
  level: info

refresh:
  interval: 1h

tasks:
  worker_count: 1
  poll_interval: 1s
  engines:
    expire_snapshots: trino
    remove_orphan_files: trino
    optimize: spark

spark:
  endpoint: sc://spark-connect-server-svc.spark:15002

sqlc:
  default:
    driver: mysql
    uri:
      host: localhost
      user: root
      password: justtrack
      database: lakehouse_admin
    migrations:
      enabled: true
      path: build/migrations

trino:
  dsn: https://user@host?catalog=lakehouse&schema=main
