app:
  env: dev
  name: lakehouse-admin

cloud:
  aws:
    defaults:
      endpoint: ""
      region: "eu-central-1"

exec:
  trino:
    backoff:
      initial_interval: 3s
      max_attempts: 0
      max_elapsed_time: 5m
      max_interval: 10s

httpserver:
  default:
    port: 8081
    mode: release
    timeout:
      read: 10m
      write: 10m

iceberg:
  catalog: lakehouse
  default_database: main
  needs_optimize_delay: 96h # 4 days

kube:
  client_mode: "in-cluster"
  context: "your-kube-config-ctx-name"

log:
  level: info

refresh:
  interval: 1h

tasks:
  worker_count: 1
  poll_interval: 1s
  engines:
    expire_snapshots: trino
    remove_orphan_files: trino
    optimize: spark
  spark:
    optimize:
      partial_progress_enabled: true
      partial_progress_max_commits: 10
      max_concurrent_file_group_rewrites: 5
  spark_callback:
    enabled: false
    backend_host: ""

spark:
  endpoint: sc://spark-connect-server-svc.spark:15002

sqlc:
  default:
    driver: mysql
    uri:
      host: localhost
      user: root
      password: justtrack
      database: lakehouse_admin
    migrations:
      enabled: true
      path: build/migrations

trino:
  backoff:
    initial_interval: 3s
    max_attempts: 0
    max_elapsed_time: 5m
    max_interval: 10s
  dsn: https://user@host?catalog=lakehouse&schema=main
