// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskClaimer creates a new instance of MockTaskClaimer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskClaimer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskClaimer {
	mock := &MockTaskClaimer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskClaimer is an autogenerated mock type for the TaskClaimer type
type MockTaskClaimer struct {
	mock.Mock
}

type MockTaskClaimer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskClaimer) EXPECT() *MockTaskClaimer_Expecter {
	return &MockTaskClaimer_Expecter{mock: &_m.Mock}
}

// ClaimTask provides a mock function for the type MockTaskClaimer
func (_mock *MockTaskClaimer) ClaimTask(ctx context.Context) (*Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClaimTask")
	}

	var r0 *Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskClaimer_ClaimTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimTask'
type MockTaskClaimer_ClaimTask_Call struct {
	*mock.Call
}

// ClaimTask is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskClaimer_Expecter) ClaimTask(ctx interface{}) *MockTaskClaimer_ClaimTask_Call {
	return &MockTaskClaimer_ClaimTask_Call{Call: _e.mock.On("ClaimTask", ctx)}
}

func (_c *MockTaskClaimer_ClaimTask_Call) Run(run func(ctx context.Context)) *MockTaskClaimer_ClaimTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskClaimer_ClaimTask_Call) Return(task *Task, err error) *MockTaskClaimer_ClaimTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskClaimer_ClaimTask_Call) RunAndReturn(run func(ctx context.Context) (*Task, error)) *MockTaskClaimer_ClaimTask_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteTask provides a mock function for the type MockTaskClaimer
func (_mock *MockTaskClaimer) CompleteTask(ctx context.Context, id int64, result map[string]any, err error) error {
	ret := _mock.Called(ctx, id, result, err)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, map[string]any, error) error); ok {
		r0 = returnFunc(ctx, id, result, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskClaimer_CompleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTask'
type MockTaskClaimer_CompleteTask_Call struct {
	*mock.Call
}

// CompleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - result map[string]any
//   - err error
func (_e *MockTaskClaimer_Expecter) CompleteTask(ctx interface{}, id interface{}, result interface{}, err interface{}) *MockTaskClaimer_CompleteTask_Call {
	return &MockTaskClaimer_CompleteTask_Call{Call: _e.mock.On("CompleteTask", ctx, id, result, err)}
}

func (_c *MockTaskClaimer_CompleteTask_Call) Run(run func(ctx context.Context, id int64, result map[string]any, err error)) *MockTaskClaimer_CompleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTaskClaimer_CompleteTask_Call) Return(err1 error) *MockTaskClaimer_CompleteTask_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockTaskClaimer_CompleteTask_Call) RunAndReturn(run func(ctx context.Context, id int64, result map[string]any, err error) error) *MockTaskClaimer_CompleteTask_Call {
	_c.Call.Return(run)
	return _c
}
