// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMaintenanceExecutor creates a new instance of MockMaintenanceExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaintenanceExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaintenanceExecutor {
	mock := &MockMaintenanceExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMaintenanceExecutor is an autogenerated mock type for the MaintenanceExecutor type
type MockMaintenanceExecutor struct {
	mock.Mock
}

type MockMaintenanceExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaintenanceExecutor) EXPECT() *MockMaintenanceExecutor_Expecter {
	return &MockMaintenanceExecutor_Expecter{mock: &_m.Mock}
}

// ExecuteExpireSnapshots provides a mock function for the type MockMaintenanceExecutor
func (_mock *MockMaintenanceExecutor) ExecuteExpireSnapshots(ctx context.Context, table string, retentionDays int, retainLast int) (*ExpireSnapshotsResult, error) {
	ret := _mock.Called(ctx, table, retentionDays, retainLast)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteExpireSnapshots")
	}

	var r0 *ExpireSnapshotsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (*ExpireSnapshotsResult, error)); ok {
		return returnFunc(ctx, table, retentionDays, retainLast)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) *ExpireSnapshotsResult); ok {
		r0 = returnFunc(ctx, table, retentionDays, retainLast)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ExpireSnapshotsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, table, retentionDays, retainLast)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceExecutor_ExecuteExpireSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteExpireSnapshots'
type MockMaintenanceExecutor_ExecuteExpireSnapshots_Call struct {
	*mock.Call
}

// ExecuteExpireSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - retentionDays int
//   - retainLast int
func (_e *MockMaintenanceExecutor_Expecter) ExecuteExpireSnapshots(ctx interface{}, table interface{}, retentionDays interface{}, retainLast interface{}) *MockMaintenanceExecutor_ExecuteExpireSnapshots_Call {
	return &MockMaintenanceExecutor_ExecuteExpireSnapshots_Call{Call: _e.mock.On("ExecuteExpireSnapshots", ctx, table, retentionDays, retainLast)}
}

func (_c *MockMaintenanceExecutor_ExecuteExpireSnapshots_Call) Run(run func(ctx context.Context, table string, retentionDays int, retainLast int)) *MockMaintenanceExecutor_ExecuteExpireSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMaintenanceExecutor_ExecuteExpireSnapshots_Call) Return(expireSnapshotsResult *ExpireSnapshotsResult, err error) *MockMaintenanceExecutor_ExecuteExpireSnapshots_Call {
	_c.Call.Return(expireSnapshotsResult, err)
	return _c
}

func (_c *MockMaintenanceExecutor_ExecuteExpireSnapshots_Call) RunAndReturn(run func(ctx context.Context, table string, retentionDays int, retainLast int) (*ExpireSnapshotsResult, error)) *MockMaintenanceExecutor_ExecuteExpireSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteOptimize provides a mock function for the type MockMaintenanceExecutor
func (_mock *MockMaintenanceExecutor) ExecuteOptimize(ctx context.Context, table string, fileSizeThresholdMb int, from time.Time, to time.Time) (*OptimizeResult, error) {
	ret := _mock.Called(ctx, table, fileSizeThresholdMb, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteOptimize")
	}

	var r0 *OptimizeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, time.Time, time.Time) (*OptimizeResult, error)); ok {
		return returnFunc(ctx, table, fileSizeThresholdMb, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, time.Time, time.Time) *OptimizeResult); ok {
		r0 = returnFunc(ctx, table, fileSizeThresholdMb, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OptimizeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, table, fileSizeThresholdMb, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceExecutor_ExecuteOptimize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteOptimize'
type MockMaintenanceExecutor_ExecuteOptimize_Call struct {
	*mock.Call
}

// ExecuteOptimize is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - fileSizeThresholdMb int
//   - from time.Time
//   - to time.Time
func (_e *MockMaintenanceExecutor_Expecter) ExecuteOptimize(ctx interface{}, table interface{}, fileSizeThresholdMb interface{}, from interface{}, to interface{}) *MockMaintenanceExecutor_ExecuteOptimize_Call {
	return &MockMaintenanceExecutor_ExecuteOptimize_Call{Call: _e.mock.On("ExecuteOptimize", ctx, table, fileSizeThresholdMb, from, to)}
}

func (_c *MockMaintenanceExecutor_ExecuteOptimize_Call) Run(run func(ctx context.Context, table string, fileSizeThresholdMb int, from time.Time, to time.Time)) *MockMaintenanceExecutor_ExecuteOptimize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMaintenanceExecutor_ExecuteOptimize_Call) Return(optimizeResult *OptimizeResult, err error) *MockMaintenanceExecutor_ExecuteOptimize_Call {
	_c.Call.Return(optimizeResult, err)
	return _c
}

func (_c *MockMaintenanceExecutor_ExecuteOptimize_Call) RunAndReturn(run func(ctx context.Context, table string, fileSizeThresholdMb int, from time.Time, to time.Time) (*OptimizeResult, error)) *MockMaintenanceExecutor_ExecuteOptimize_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteRemoveOrphanFiles provides a mock function for the type MockMaintenanceExecutor
func (_mock *MockMaintenanceExecutor) ExecuteRemoveOrphanFiles(ctx context.Context, table string, retentionDays int) (*RemoveOrphanFilesResult, error) {
	ret := _mock.Called(ctx, table, retentionDays)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteRemoveOrphanFiles")
	}

	var r0 *RemoveOrphanFilesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (*RemoveOrphanFilesResult, error)); ok {
		return returnFunc(ctx, table, retentionDays)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) *RemoveOrphanFilesResult); ok {
		r0 = returnFunc(ctx, table, retentionDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RemoveOrphanFilesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, table, retentionDays)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteRemoveOrphanFiles'
type MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call struct {
	*mock.Call
}

// ExecuteRemoveOrphanFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - retentionDays int
func (_e *MockMaintenanceExecutor_Expecter) ExecuteRemoveOrphanFiles(ctx interface{}, table interface{}, retentionDays interface{}) *MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call {
	return &MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call{Call: _e.mock.On("ExecuteRemoveOrphanFiles", ctx, table, retentionDays)}
}

func (_c *MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call) Run(run func(ctx context.Context, table string, retentionDays int)) *MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call) Return(removeOrphanFilesResult *RemoveOrphanFilesResult, err error) *MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call {
	_c.Call.Return(removeOrphanFilesResult, err)
	return _c
}

func (_c *MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call) RunAndReturn(run func(ctx context.Context, table string, retentionDays int) (*RemoveOrphanFilesResult, error)) *MockMaintenanceExecutor_ExecuteRemoveOrphanFiles_Call {
	_c.Call.Return(run)
	return _c
}
