// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gosoline-project/sqlc"
	"github.com/justtrackio/lakehouse-admin/internal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSnapshotRefresher creates a new instance of MockSnapshotRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotRefresher {
	mock := &MockSnapshotRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotRefresher is an autogenerated mock type for the SnapshotRefresher type
type MockSnapshotRefresher struct {
	mock.Mock
}

type MockSnapshotRefresher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotRefresher) EXPECT() *MockSnapshotRefresher_Expecter {
	return &MockSnapshotRefresher_Expecter{mock: &_m.Mock}
}

// RefreshSnapshots provides a mock function for the type MockSnapshotRefresher
func (_mock *MockSnapshotRefresher) RefreshSnapshots(cttx sqlc.Tx, table string) ([]internal.Snapshot, error) {
	ret := _mock.Called(cttx, table)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSnapshots")
	}

	var r0 []internal.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sqlc.Tx, string) ([]internal.Snapshot, error)); ok {
		return returnFunc(cttx, table)
	}
	if returnFunc, ok := ret.Get(0).(func(sqlc.Tx, string) []internal.Snapshot); ok {
		r0 = returnFunc(cttx, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sqlc.Tx, string) error); ok {
		r1 = returnFunc(cttx, table)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotRefresher_RefreshSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSnapshots'
type MockSnapshotRefresher_RefreshSnapshots_Call struct {
	*mock.Call
}

// RefreshSnapshots is a helper method to define mock.On call
//   - cttx sqlc.Tx
//   - table string
func (_e *MockSnapshotRefresher_Expecter) RefreshSnapshots(cttx interface{}, table interface{}) *MockSnapshotRefresher_RefreshSnapshots_Call {
	return &MockSnapshotRefresher_RefreshSnapshots_Call{Call: _e.mock.On("RefreshSnapshots", cttx, table)}
}

func (_c *MockSnapshotRefresher_RefreshSnapshots_Call) Run(run func(cttx sqlc.Tx, table string)) *MockSnapshotRefresher_RefreshSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sqlc.Tx
		if args[0] != nil {
			arg0 = args[0].(sqlc.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotRefresher_RefreshSnapshots_Call) Return(snapshots []internal.Snapshot, err error) *MockSnapshotRefresher_RefreshSnapshots_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *MockSnapshotRefresher_RefreshSnapshots_Call) RunAndReturn(run func(cttx sqlc.Tx, table string) ([]internal.Snapshot, error)) *MockSnapshotRefresher_RefreshSnapshots_Call {
	_c.Call.Return(run)
	return _c
}
